spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: "true"
        use_sql_comments: "true"
        # show_sql: "true"
    hibernate:
      ddl-auto: create
